name: Build and publish images

on:
  workflow_dispatch:

  schedule:
    # chosen by fair dice roll
    - cron: '42 22 * * 3'
  push:
    branches:
      - main

jobs:
  publish:
    name: Build and test images
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits[0].message, '[skip ci]') && !contains(github.event.commits[0].message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Build Docker Image
        run: docker compose build
      - name: Publish Docker Image
        run: docker compose push